services:
  - type: web
    name: QUEEN-NEZUKO
    env: node
    branch: main
    repo: https://github.com/godzenitsu/Queen-Nezuko.git
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
